# Use three(3) white spaces, tab indentations are not allowed
users:
   default: 
   
# Warning: Do not change url values.
urls:
   bambooUrl: "http://bamboo.champ.aero:8085/browse/${keyPlan}"
   stopRedirectUrl: "http://bamboo.champ.aero:8085/build/admin/stopPlan.action?planResultKey=${keyPlan}-{}&returnUrl=%2Fbrowse%2F${keyPlan}-{}"
   restartStopUrl: "http://${hostName}.champ.aero:8080/notifier/cancelNotify?method=restart&user={}&buildNum={}"
   deployStopUrl: "http://${hostName}.champ.aero:8080/notifier/cancelNotify?method=deploy&user={}&buildNum={}"
   
# Warning: for messages, avoid modifying any variables, formats or special characters.
messages:
   restartMsg: "I will restart ${team} IE in {}.<br> Let me know if I should wait. :) <br>"
   deployMsg: "I will deploy ${team} IE in {}.<br> Let me know if I should wait. :) <br>"
   restartDoneMsg: "Restart done via <a href={}>{}</a><br> Thank you. :)"
   deployDoneMsg: "Deploy done via <a href={}>{}</a><br> Bamboo Build Number: <strong>{}</strong><br> Thank you. :)"
   restartStopMsg: "<a href={}>If you wish to stop the restart, click here<br>"
   deployStopMsg: "<a href={}>If you wish to stop the deployment, click here<br>"
   restartStopDoneMsg: "The restart has been stopped. \r\n"
   deployStopDoneMsg: "The deployment has been stopped. \r\n"
   restartStopNotDoneMsg: "Cannot stop the restart. \r\n Time limit for waiting time has been reached!\r\n"
   deployStopNotDoneMsg: "Cannot stop the deployment. \r\n Time limit for waiting time has been reached!\r\n"
   restartSubjectMsg: "${team} IE Restart"
   deploySubjectMsg: "${team} IE Deployment"
   
recipients:
   
team: 

keyPlan:

hostName: 