# Use three(3) white spaces, tab indentations are not allowed
users:
   default: 
   
urls:
   
messages:
   restartMsg: "I will restart ${team} IE in {}.<br> Let me know if I should wait. :) <br>"
   deployMsg: "I will deploy ${team} IE in {}.<br> Let me know if I should wait. :) <br>"
   restartDoneMsg: "Restart done via <a href={}>{}</a><br> Thank you. :)"
   deployDoneMsg: "Deploy done via <a href={}>{}</a><br> Thank you. :)"
   restartStopMsg: "<a href={}>If you wish to stop the restart, click here<br>"
   deployStopMsg: "<a href={}>If you wish to stop the deployment, click here<br>"
   restartStopDoneMsg: "The restart has been stopped. \r\n"
   deployStopDoneMsg: "The deployment has been stopped. \r\n"
   restartStopNotDoneMsg: "Cannot stop the restart. \r\n Time limit for waiting time has been reached!\r\n"
   deployStopNotDoneMsg: "Cannot stop the deployment. \r\n Time limit for waiting time has been reached!\r\n"
   restartSubjectMsg: "${team} IE Restart"
   deploySubjectMsg: "${team} IE Deployment"
   
recipients:
   
team: 
    